"""
Script 1: build_crosswalk.py
Maps each outline session to ITE PrimaryCategory + Subcategory_Cluster values.
Output: session_cluster_crosswalk.csv  (human review before injection)
"""

import zipfile, re, csv, os
from pathlib import Path

SCRIPT_DIR   = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
DOCX_PATH    = SCRIPT_DIR.parent / "source" / "00_EX_content_outline_w_q.docx"
OUTPUT_PATH  = PROJECT_ROOT / "key_data_files" / "session_cluster_crosswalk.csv"

# session_number, session_name, primary_categories, top_clusters (priority order), notes
CROSSWALK = [
    ("02", "Peripheral Vascular Disease",
     "Cardiovascular",
     "Cardiovascular_C3,Cardiovascular_C5,Cardiovascular_C2",
     "PAD, HTN, vascular meds"),
    ("03", "Acute Coronary Syndrome & Hyperlipidemia",
     "Cardiovascular",
     "Cardiovascular_C3,Cardiovascular_C5,Cardiovascular_C4",
     "ACS, lipid meds, cardiac history"),
    ("04", "Hypertension",
     "Cardiovascular,Endocrine,Nephrologic",
     "Cardiovascular_C2,Cardiovascular_C5,Endocrine_C2",
     "BP values, antihypertensives, CKD-HTN"),
    ("05", "Heart Failure",
     "Cardiovascular",
     "Cardiovascular_C3,Cardiovascular_C5,Cardiovascular_C4",
     "HF management, medications"),
    ("06", "Managing Dysrhythmias",
     "Cardiovascular",
     "Cardiovascular_C6,Cardiovascular_C3,Cardiovascular_C4",
     "A-fib, anticoagulation, rhythm mgmt"),
    ("07", "Health Promotion & Prevention",
     "Population-Based Care",
     "Population-Based Care_C1,Population-Based Care_C2,Population-Based Care_C5",
     "Screening, prevention, vaccines"),
    ("08", "Epidemiology & Medical Literature",
     "Population-Based Care,Patient-Based Systems",
     "Population-Based Care_C1,Patient-Based Systems_C1",
     "Stats, evidence-based medicine"),
    ("09", "Managing Common Cutaneous Problems",
     "Integumentary",
     "Integumentary_C3,Integumentary_C2,Integumentary_C1",
     "Skin conditions, topical/oral tx"),
    ("10", "Emergency Medicine I",
     "Cardiovascular,Respiratory",
     "Cardiovascular_C3,Respiratory_C3,Respiratory_C5",
     "Acute cardiac, respiratory emergencies"),
    ("11", "Emergency Medicine II",
     "Hematologic/Immune,Neurologic",
     "Hematologic/Immune_C4,Neurologic_C1,Hematologic/Immune_C2",
     "Toxicology, neuro emergencies"),
    ("12", "Emergency Medicine III",
     "Musculoskeletal,Cardiovascular",
     "Musculoskeletal_C2,Cardiovascular_C3,Cardiovascular_C4",
     "Trauma, ortho emergencies"),
    ("13", "Obesity & Metabolic Syndrome",
     "Endocrine",
     "Endocrine_C1,Endocrine_C2,Endocrine_C4",
     "BMI, metabolic meds, obesity tx"),
    ("14", "Diabetes Mellitus",
     "Endocrine",
     "Endocrine_C2,Endocrine_C4,Endocrine_C3",
     "Diabetes management, medications, A1C"),
    ("15", "Endocrine Diseases",
     "Endocrine",
     "Endocrine_C3,Endocrine_C2,Endocrine_C1",
     "Thyroid, adrenal, other endocrine"),
    ("16", "Lower GI Tract Diseases",
     "Gastrointestinal",
     "Gastrointestinal_C2,Gastrointestinal_C3,Gastrointestinal_C4",
     "IBD, diverticular, colorectal"),
    ("17", "Upper GI Tract Diseases",
     "Gastrointestinal",
     "Gastrointestinal_C2,Gastrointestinal_C3,Gastrointestinal_C1",
     "GERD, peptic ulcer, liver disease"),
    ("18", "Geriatrics I: Systems of Care & Cognitive Impairment",
     "Patient-Based Systems,Neurologic",
     "Patient-Based Systems_C1,Patient-Based Systems_C2,Neurologic_C1",
     "Dementia, care systems, decision-making"),
    ("19", "Geriatrics II: Osteoporosis, Gait & Prevention",
     "Musculoskeletal,Population-Based Care",
     "Musculoskeletal_C1,Musculoskeletal_C4,Population-Based Care_C4",
     "Osteoporosis, falls, elder prevention"),
    ("20", "Geriatrics III: Pharmacokinetics & Polypharmacy",
     "Patient-Based Systems,Endocrine",
     "Patient-Based Systems_C2,Endocrine_C2,Musculoskeletal_C1",
     "Polypharmacy, Beers criteria, drug dosing"),
    ("21", "Hematology Issues",
     "Hematologic/Immune",
     "Hematologic/Immune_C4,Hematologic/Immune_C3,Hematologic/Immune_C2",
     "Anemia, thrombocytopenia, coagulopathy"),
    ("22", "Fever & Infectious Disease in Children",
     "Population-Based Care,Hematologic/Immune",
     "Population-Based Care_C4,Population-Based Care_C5,Hematologic/Immune_C4",
     "Peds ID, vaccines, fever workup"),
    ("23", "STIs, Vaginitis & Vaginosis",
     "Reproductive:Female,Reproductive:Male",
     "Reproductive:Female_C2,Reproductive:Male_C1,Reproductive:Female_C1",
     "STI tx, vaginitis, GU infections"),
    ("24", "Renal Disease I",
     "Nephrologic",
     "Nephrologic_C2,Nephrologic_C1,Nephrologic_C3",
     "CKD, AKI, renal labs"),
    ("25", "Renal Disease II",
     "Nephrologic",
     "Nephrologic_C3,Nephrologic_C2,Nephrologic_C1",
     "Stones, urinalysis, electrolytes"),
    ("26", "Common Neurological Disorders",
     "Neurologic",
     "Neurologic_C1,Neurologic_C3,Neurologic_C2",
     "Headache, stroke, weakness, hearing"),
    ("27", "Maternity Care I: Prenatal Care & Early Complications",
     "Reproductive:Female",
     "Reproductive:Female_C3,Reproductive:Female_C2,Reproductive:Female_C4",
     "Prenatal screening, ectopic, early complications"),
    ("28", "Maternity Care II: Medical Complications & Labor Management",
     "Reproductive:Female",
     "Reproductive:Female_C3,Reproductive:Female_C4,Reproductive:Female_C2",
     "Preeclampsia, GDM, labor"),
    ("29", "Women's Health I: AUB & Gynecologic Oncology",
     "Reproductive:Female",
     "Reproductive:Female_C1,Reproductive:Female_C2,Reproductive:Female_C3",
     "AUB, cervical/endometrial cancer, colposcopy"),
    ("30", "Women's Health II: Breast Issues, Contraception & Infertility",
     "Reproductive:Female,Population-Based Care",
     "Reproductive:Female_C1,Population-Based Care_C3,Reproductive:Female_C4",
     "Contraception, breast cancer, infertility"),
    ("31", "Musculoskeletal Medicine",
     "Musculoskeletal",
     "Musculoskeletal_C4,Musculoskeletal_C2,Musculoskeletal_C3",
     "Arthritis, soft tissue, general MSK"),
    ("32", "Fracture Care",
     "Musculoskeletal",
     "Musculoskeletal_C2,Musculoskeletal_C4,Musculoskeletal_C6",
     "Fractures, splinting, ortho mgmt"),
    ("33", "Sports Medicine",
     "Musculoskeletal",
     "Musculoskeletal_C3,Musculoskeletal_C5,Musculoskeletal_C2",
     "Knee, shoulder, sports injuries"),
    ("34", "Pediatric Orthopedics",
     "Musculoskeletal",
     "Musculoskeletal_C4,Musculoskeletal_C2,Musculoskeletal_C6",
     "Peds fractures, developmental issues"),
    ("35", "Common ENT Problems",
     "Special Sensory,Respiratory",
     "Special Sensory_C1,Special Sensory_C2,Respiratory_C4",
     "Ear, nose, throat, hearing loss"),
    ("36", "Management of Chronic Pain",
     "Musculoskeletal,Patient-Based Systems",
     "Musculoskeletal_C1,Musculoskeletal_C4,Patient-Based Systems_C1",
     "Pain meds, opioid management, chronic pain"),
    ("37", "Common Newborn Issues",
     "Population-Based Care,Hematologic/Immune",
     "Population-Based Care_C4,Hematologic/Immune_C3,Population-Based Care_C5",
     "Newborn screen, jaundice, neonatal"),
    ("38", "Well-Child & Adolescent Issues",
     "Population-Based Care",
     "Population-Based Care_C4,Population-Based Care_C5,Population-Based Care_C1",
     "Well-child, vaccines, adolescent health"),
    ("39", "Behavioral Medicine I: Depression",
     "Psychogenic",
     "Psychogenic_C3,Psychogenic_C4,Psychogenic_C2",
     "Depression, antidepressants, therapy"),
    ("40", "Behavioral Medicine II: Bipolar & Anxiety Disorders",
     "Psychogenic",
     "Psychogenic_C2,Psychogenic_C3,Psychogenic_C4",
     "Bipolar, anxiety, mood stabilizers"),
    ("41", "Behavioral Medicine III: ADHD, Autism & OCD",
     "Psychogenic",
     "Psychogenic_C1,Psychogenic_C3,Psychogenic_C2",
     "ADHD, autism spectrum, OCD"),
    ("42", "Pulmonary I: COPD",
     "Respiratory",
     "Respiratory_C1,Respiratory_C2,Respiratory_C3",
     "COPD, spirometry, inhaled meds"),
    ("43", "Pulmonary II: Asthma",
     "Respiratory",
     "Respiratory_C2,Respiratory_C3,Respiratory_C1",
     "Asthma, inhaled therapy, exacerbation"),
    ("44", "Pulmonary III: Pulmonary Infections & Pneumonia Part 1",
     "Respiratory",
     "Respiratory_C4,Respiratory_C2,Respiratory_C5",
     "Pneumonia, influenza, CAP/HAP"),
    ("45", "Pulmonary IV: Infections, Pneumonia Part 2 & Occupational Lung Disease",
     "Respiratory",
     "Respiratory_C4,Respiratory_C5,Respiratory_C2",
     "Atypical pneumonia, occupational, TB"),
    ("46", "Pulmonary V: Lung Cancer, OSA, Sarcoidosis & Pulmonary Fibrosis",
     "Respiratory,Population-Based Care",
     "Respiratory_C5,Population-Based Care_C2,Respiratory_C1",
     "Lung cancer screening, OSA, ILD"),
    ("47", "The Major Arthritides",
     "Musculoskeletal,Hematologic/Immune",
     "Musculoskeletal_C4,Musculoskeletal_C3,Hematologic/Immune_C4",
     "RA, gout, OA, SLE, arthritis workup"),
    ("48", "Preoperative Examination & Management",
     "Patient-Based Systems,Cardiovascular",
     "Patient-Based Systems_C1,Cardiovascular_C3,Cardiovascular_C5",
     "Pre-op risk, cardiac clearance, meds mgmt"),
    ("49", "Urologic Problems",
     "Reproductive:Male,Nephrologic",
     "Reproductive:Male_C2,Nephrologic_C3,Reproductive:Male_C1",
     "BPH, prostate, urologic conditions"),
]

with open(OUTPUT_PATH, 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(['session_number', 'session_name', 'primary_categories', 'top_clusters', 'notes'])
    for row in CROSSWALK:
        writer.writerow(row)

print(f"Crosswalk written to: {OUTPUT_PATH}")
print(f"Sessions mapped: {len(CROSSWALK)}")
